### ISSUE TITLE
feature request: b4 option to sort trailers

### ISSUE THREAD

**Issue by floatious** [mricon/b4#20]
It would be nice if there either was an option for b4 to sort trailers by default,
or to add an option to do so.

After using $ b4 shazam -s -t <mail-id>

I get:
    Reviewed-by: aaa
    Tested-by: aaa
    Reviewed-by: bbb
    Tested-by: ccc
    Reviewed-by: ddd
    Signed-off-by: eee

I don't know if this is because I used -t (some trailers were given on the cover letter).

But at least I would prefer to have:
    Tested-by: aaa
    Tested-by: ccc
    Reviewed-by: aaa
    Reviewed-by: bbb
    Reviewed-by: ddd
    Signed-off-by: eee

So that the R-b and T-b are grouped together.

**Comment by mricon** [comment]
This is supported (within the custody boundaries) by the `trailer-order` config option, see https://b4.docs.kernel.org/en/latest/config.html.
