### ISSUE TITLE
improvements to static typing?

### ISSUE THREAD

**Issue by tamird** [mricon/b4#49]
Hey, thanks for making this awesome tool! I was browsing around the sources and noticed that there are quite a few type errors (some real, some not).

Would you be interested in contributions that improve the typings?
Would you be interested in contributions adding CI to check typings with mypy and pyright?

**Comment by mricon** [comment]
Sure, I'll always accept contributions like that. I generally work to the point where PyCharm is showing all checks passing, but I know there are more stringent checkers.

Note, that I rarely check github, so your best bet is to communicate via tools@kernel.org.
