### ISSUE TITLE
Allow sorting developer signatures when creating mbox

### ISSUE THREAD

**Issue by glaubitz** [mricon/b4#8]
When importing patches from a mailing list thread, `b4` adds the developer signatures it finds in the thread. While that works very well, the sorting order of the signatures in the commit message the patches seems rather non-deterministic.

In order to increase readability, it would be nice if there was an option to sort the signatures by developer name while keeping the `Signed-off-by` of the author at the top and the `Signed-off-by` of the subsystem maintainer at the bottom.

**Comment by mricon** [comment]
The signed-off-by order is deterministic and follows the chain-of-custody rules. See the documentation for "trailer-order": https://b4.docs.kernel.org/en/latest/config.html#core-options
